gcloud services enable bigquery-json.googleapis.com
gcloud services enable cloudresourcemanager.googleapis.com
gcloud services enable appengine.googleapis.com
gcloud services enable cloudbuild.googleapis.com
gcloud services enable iam.googleapis.com
gcloud services enable iamcredentials.googleapis.com
gcloud services enable cloudkms.googleapis.com
gcloud services enable cloudscheduler.googleapis.com
gcloud services enable cloudfunctions.googleapis.com
gcloud services enable pubsub.googleapis.com
gcloud services enable sourcerepo.googleapis.com
gcloud services enable run.googleapis.com
gcloud services enable dataflow.googleapis.com
gcloud services enable composer.googleapis.com
gcloud services enable secretmanager.googleapis.com
gcloud services enable artifactregistry.googleapis.com
gcloud services enable containerregistry.googleapis.com
gcloud services enable bigquerydatatransfer.googleapis.com
gcloud services enable compute.googleapis.com
gcloud services enable cloudiot.googleapis.com
